name: Cleanup Old S3 Files

on:
  schedule:
    # Cleanup old S3 files - every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  cleanup-old-s3-files:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Old S3 Files
        run: |
          curl -sS -X POST https://walrus-jpfl.onrender.com/api/cleanup/s3-old-files
