name: Retry Failed Uploads

on:
  schedule:
    # Retry failed uploads - every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  retry-failed-uploads:
    runs-on: ubuntu-latest
    steps:
      - name: Retry Failed Uploads
        run: |
          curl -sS -X POST http://169.231.231.63:3000/api/upload/retry-failed
