name: Trigger Pending Uploads

on:
  schedule:
    # Trigger pending uploads - every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  trigger-pending-uploads:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pending Uploads
        run: |
          curl -sS -X POST http://169.231.231.63:3000/api/upload/trigger-pending
